version: "3.9"
services:
    mariadb:
        image: inception-mariadb
        container_name: inception-mariadb
        volumes:
            - ~/data/db:/var/lib/mysql
        environment:
            - DB_USER_ADMIN=${DB_USER_ADMIN}
            - DB_PASSWORD_ADMIN=${DB_PASSWORD_ADMIN}
            - DB_USER_REG=${DB_USER_REG}
            - DB_PASSWORD_REG=${DB_PASSWORD_REG}
        restart: always
    nginx:
        image: inception-nginx
        container_name: inception-nginx
        ports:
            - 443:443
            - 80:80
        restart: always
    wordpress:
        image: inception-wordpress
        container_name: inception-wordpress
        volumes:
            - ~/data/wp:/var/www/html
        environment:
            - DB_USER_ADMIN=${DB_USER_ADMIN}
            - DB_PASSWORD_ADMIN=${DB_PASSWORD_ADMIN}
            - DB_USER_REG=${DB_USER_REG}
            - DB_PASSWORD_REG=${DB_PASSWORD_REG}
        restart: always